### ISSUE TITLE
Seed new notification types with contents to DB

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/Roadmap#31]

**Comment by mohammadranjbarz** [comment]
Add new notification types based on https://docs.google.com/spreadsheets/d/1VMsmF9oJEwf1JyNEAfWi2n2eYvG6ZtnkXKB_3Hv29x8/edit#gid=0

**Comment by MohammadPCh** [comment]
@mohammadranjbarz @MoeNick 
I have converted the sheet to JSON and added template and content properties to the elements with OK status.
please be aware that it's easier to change this file and post it here instead of updating that sheet because converting that sheet to this JSON takes time and is done manually.
https://gist.github.com/MohammadPCh/24434d50bc9ccd9b74905c271ee05482

**Comment by MoeNick** [comment]
Issue moved to [Giveth/impact-graph #684](https://github.com/Giveth/impact-graph/issues/684) via [**Zenhub**](https://www.zenhub.com/)

**Comment by CarlosQ96** [comment]
@MohammadPCh thanks for being awesome for that Json
